services:
  mysql-server:
    image: mysql:8.0-oracle
    container_name: mysql-server
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pwd
      MYSQL_ROOT_PASSWORD: root_pwd
    command:
      --character-set-server=utf8 --collation-server=utf8_bin --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    networks:
      zabbix-net:
        ipv4_address: 172.20.240.2

  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:alpine-7.2-latest
    container_name: zabbix-server-mysql
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pwd
      MYSQL_ROOT_PASSWORD: root_pwd
    ports:
      - "10051:10051"
    depends_on:
      - mysql-server
    restart: unless-stopped
    networks:
      zabbix-net:
        ipv4_address: 172.20.240.4

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-7.2-latest
    container_name: zabbix-web-nginx-mysql
    environment:
      ZBX_SERVER_HOST: zabbix-server-mysql
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pwd
      MYSQL_ROOT_PASSWORD: root_pwd
      PHP_TZ: America/Sao_Paulo
    ports:
      - "8080:8080"
    depends_on:
      - zabbix-server-mysql
    restart: unless-stopped
    networks:
      zabbix-net:
        ipv4_address: 172.20.240.5

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      zabbix-net:
        ipv4_address: 172.20.240.6
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      zabbix-net:
        ipv4_address: 172.20.240.7


networks:
  zabbix-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.240.0/20
