services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    networks:
      - zabbix-net
    restart: unless-stopped
  mysql-server:
    image: mysql:8.3
    container_name: mysql-server
    environment:
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
      MYSQL_ROOT_PASSWORD: "zabbix"
    command: --character-set-server=utf8 --collation-server=utf8_bin
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - zabbix-net

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: "mysql-server"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
      MYSQL_ROOT_PASSWORD: "zabbix"
    depends_on:
      - mysql-server
    ports:
      - "10051:10051"
    restart: unless-stopped
    networks:
      - zabbix-net

  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:latest
    container_name: zabbix-web
    environment:
      ZBX_SERVER_HOST: "zabbix-server"
      DB_SERVER_HOST: "mysql-server"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
      MYSQL_ROOT_PASSWORD: "zabbix"
      PHP_TZ: "America/Sao_Paulo"
    depends_on:
      - zabbix-server
    #ports:
     # - "80:8080"
    restart: unless-stopped
    networks:
      - zabbix-net

  zabbix-agent2:
    image: zabbix/zabbix-agent2:latest
    container_name: zabbix-agent2
    environment:
      ZBX_HOSTNAME: "Zabbix server"
      ZBX_SERVER_HOST: "zabbix-server"
    depends_on:
      - zabbix-server
    restart: always
    networks:
      - zabbix-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes: 
      - prometheus-data:/etc/prometheus
    command:  "--config.file=/etc/prometheus/prometheus.yml"
    #ports:
    #  - "9090:9090"
    restart: unless-stopped
    networks:
      - zabbix-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=admin
    - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/plugins:/etc/grafana/provisioning/plugins
    #ports:
     # - "3000:3000"
    restart: unless-stopped
    networks:
      - zabbix-net

volumes:
  mysql-data:
  prometheus-data:
  grafana-data:

networks:
  zabbix-net:
    driver: bridge