global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Exemplo de alvo para o Laravel ou outro app
  - job_name: 'meu-app'
    static_configs:
      - targets: ['host.docker.internal:9100']
